package com.livewire.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val Seed = Color(0xFFFFA500)

val PrimaryLight = Color(0xFF815100)
val OnPrimaryLight = Color(0xFFFFF0E3)
val PrimaryContainerLight = Color(0xFFFFA504)
val OnPrimaryContainerLight = Color(0xFF4F3000)
val InversePrimaryLight = Color(0xFFFFA504)
val SecondaryLight = Color(0xFFBB0003)
val OnSecondaryLight = Color(0xFFFFEFED)
val SecondaryContainerLight = Color(0xFFFFC3BA)
val OnSecondaryContainerLight = Color(0xFF940002)
val TertiaryLight = Color(0xFF6E5A00)
val OnTertiaryLight = Color(0xFFFFF2D0)
val TertiaryContainerLight = Color(0xFFFED73E)
val OnTertiaryContainerLight = Color(0xFF5C4B00)
val BackgroundLight = Color(0xFFFEF8F5)
val OnBackgroundLight = Color(0xFF36322E)
val SurfaceLight = Color(0xFFFEF8F5)
val OnSurfaceLight = Color(0xFF36322E)
val SurfaceVariantLight = Color(0xFFE9E1DB)
val OnSurfaceVariantLight = Color(0xFF635E59)
val SurfaceTintLight = Color(0xFF855400)
val InverseSurfaceLight = Color(0xFF0F0E0C)
val InverseOnSurfaceLight = Color(0xFFA09C99)
val ErrorLight = Color(0xFF9E422C)
val OnErrorLight = Color(0xFFFFF7F6)
val ErrorContainerLight = Color(0xFFFE8B70)
val OnErrorContainerLight = Color(0xFF742410)
val OutlineLight = Color(0xFF807A75)
val OutlineVariantLight = Color(0xFFB8B1AB)
val ScrimLight = Color(0xFF000000)
val SurfaceBrightLight = Color(0xFFFEF8F5)
val SurfaceContainerLight = Color(0xFFF4ECE8)
val SurfaceContainerHighLight = Color(0xFFEFE7E1)
val SurfaceContainerHighestLight = Color(0xFFE9E1DB)
val SurfaceContainerLowLight = Color(0xFFF9F2EE)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceDimLight = Color(0xFFE1D8D2)

val PrimaryDark = Color(0xFFFFB95C)
val OnPrimaryDark = Color(0xFF5C3800)
val PrimaryContainerDark = Color(0xFFFFA504)
val OnPrimaryContainerDark = Color(0xFF4F3000)
val InversePrimaryDark = Color(0xFF855400)
val SecondaryDark = Color(0xFFFF725F)
val OnSecondaryDark = Color(0xFF4A0000)
val SecondaryContainerDark = Color(0xFFC00003)
val OnSecondaryContainerDark = Color(0xFFFFF6F4)
val TertiaryDark = Color(0xFFFFE799)
val OnTertiaryDark = Color(0xFF665300)
val TertiaryContainerDark = Color(0xFFFED73E)
val OnTertiaryContainerDark = Color(0xFF5C4B00)
val BackgroundDark = Color(0xFF0F0E0C)
val OnBackgroundDark = Color(0xFFECE4DE)
val SurfaceDark = Color(0xFF0F0E0C)
val OnSurfaceDark = Color(0xFFECE4DE)
val SurfaceVariantDark = Color(0xFF292521)
val OnSurfaceVariantDark = Color(0xFFB1AAA4)
val SurfaceTintDark = Color(0xFFFFB95C)
val InverseSurfaceDark = Color(0xFFFEF8F5)
val InverseOnSurfaceDark = Color(0xFF575452)
val ErrorDark = Color(0xFFED7F64)
val OnErrorDark = Color(0xFF450900)
val ErrorContainerDark = Color(0xFF7E2B17)
val OnErrorContainerDark = Color(0xFFFF9B82)
val OutlineDark = Color(0xFF7A746F)
val OutlineVariantDark = Color(0xFF4C4743)
val ScrimDark = Color(0xFF000000)
val SurfaceBrightDark = Color(0xFF302B27)
val SurfaceContainerDark = Color(0xFF1C1917)
val SurfaceContainerHighDark = Color(0xFF221F1C)
val SurfaceContainerHighestDark = Color(0xFF292521)
val SurfaceContainerLowDark = Color(0xFF151311)
val SurfaceContainerLowestDark = Color(0xFF000000)
val SurfaceDimDark = Color(0xFF0F0E0C)

val PrimaryFixed = Color(0xFFFFA504)
val PrimaryFixedDim = Color(0xFFED9900)
val OnPrimaryFixed = Color(0xFF311C00)
val OnPrimaryFixedVariant = Color(0xFF5B3800)
val SecondaryFixed = Color(0xFFFFC3BA)
val SecondaryFixedDim = Color(0xFFFFB0A4)
val OnSecondaryFixed = Color(0xFF700001)
val OnSecondaryFixedVariant = Color(0xFFA60002)
val TertiaryFixed = Color(0xFFFED73E)
val TertiaryFixedDim = Color(0xFFEFC930)
val OnTertiaryFixed = Color(0xFF463900)
val OnTertiaryFixedVariant = Color(0xFF675400)
val PrimaryPaletteKeyColor = Color(0xFFFFA500)
val SecondaryPaletteKeyColor = Color(0xFFF40B0B)
val TertiaryPaletteKeyColor = Color(0xFFCEAB00)
val NeutralPaletteKeyColor = Color(0xFF91723B)
val NeutralVariantPaletteKeyColor = Color(0xFF977126)
val ErrorPaletteKeyColor = Color(0xFFD9401B)

fun defaultLightColorScheme(): ColorScheme = lightColorScheme(
  primary = PrimaryLight,
  onPrimary = OnPrimaryLight,
  primaryContainer = PrimaryContainerLight,
  onPrimaryContainer = OnPrimaryContainerLight,
  inversePrimary = InversePrimaryLight,
  secondary = SecondaryLight,
  onSecondary = OnSecondaryLight,
  secondaryContainer = SecondaryContainerLight,
  onSecondaryContainer = OnSecondaryContainerLight,
  tertiary = TertiaryLight,
  onTertiary = OnTertiaryLight,
  tertiaryContainer = TertiaryContainerLight,
  onTertiaryContainer = OnTertiaryContainerLight,
  background = BackgroundLight,
  onBackground = OnBackgroundLight,
  surface = SurfaceLight,
  onSurface = OnSurfaceLight,
  surfaceVariant = SurfaceVariantLight,
  onSurfaceVariant = OnSurfaceVariantLight,
  surfaceTint = SurfaceTintLight,
  inverseSurface = InverseSurfaceLight,
  inverseOnSurface = InverseOnSurfaceLight,
  error = ErrorLight,
  onError = OnErrorLight,
  errorContainer = ErrorContainerLight,
  onErrorContainer = OnErrorContainerLight,
  outline = OutlineLight,
  outlineVariant = OutlineVariantLight,
  scrim = ScrimLight,
  surfaceBright = SurfaceBrightLight,
  surfaceContainer = SurfaceContainerLight,
  surfaceContainerHigh = SurfaceContainerHighLight,
  surfaceContainerHighest = SurfaceContainerHighestLight,
  surfaceContainerLow = SurfaceContainerLowLight,
  surfaceContainerLowest = SurfaceContainerLowestLight,
  surfaceDim = SurfaceDimLight,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)

fun defaultDarkColorScheme(): ColorScheme = darkColorScheme(
  primary = PrimaryDark,
  onPrimary = OnPrimaryDark,
  primaryContainer = PrimaryContainerDark,
  onPrimaryContainer = OnPrimaryContainerDark,
  inversePrimary = InversePrimaryDark,
  secondary = SecondaryDark,
  onSecondary = OnSecondaryDark,
  secondaryContainer = SecondaryContainerDark,
  onSecondaryContainer = OnSecondaryContainerDark,
  tertiary = TertiaryDark,
  onTertiary = OnTertiaryDark,
  tertiaryContainer = TertiaryContainerDark,
  onTertiaryContainer = OnTertiaryContainerDark,
  background = BackgroundDark,
  onBackground = OnBackgroundDark,
  surface = SurfaceDark,
  onSurface = OnSurfaceDark,
  surfaceVariant = SurfaceVariantDark,
  onSurfaceVariant = OnSurfaceVariantDark,
  surfaceTint = SurfaceTintDark,
  inverseSurface = InverseSurfaceDark,
  inverseOnSurface = InverseOnSurfaceDark,
  error = ErrorDark,
  onError = OnErrorDark,
  errorContainer = ErrorContainerDark,
  onErrorContainer = OnErrorContainerDark,
  outline = OutlineDark,
  outlineVariant = OutlineVariantDark,
  scrim = ScrimDark,
  surfaceBright = SurfaceBrightDark,
  surfaceContainer = SurfaceContainerDark,
  surfaceContainerHigh = SurfaceContainerHighDark,
  surfaceContainerHighest = SurfaceContainerHighestDark,
  surfaceContainerLow = SurfaceContainerLowDark,
  surfaceContainerLowest = SurfaceContainerLowestDark,
  surfaceDim = SurfaceDimDark,
  primaryFixed = PrimaryFixed,
  primaryFixedDim = PrimaryFixedDim,
  onPrimaryFixed = OnPrimaryFixed,
  onPrimaryFixedVariant = OnPrimaryFixedVariant,
  secondaryFixed = SecondaryFixed,
  secondaryFixedDim = SecondaryFixedDim,
  onSecondaryFixed = OnSecondaryFixed,
  onSecondaryFixedVariant = OnSecondaryFixedVariant,
  tertiaryFixed = TertiaryFixed,
  tertiaryFixedDim = TertiaryFixedDim,
  onTertiaryFixed = OnTertiaryFixed,
  onTertiaryFixedVariant = OnTertiaryFixedVariant,
)
